version: 1
handlers:
  # 我们定义了两个处理程序 console 和 audit_file
  console:
    class: logging.StreamHandler
    stream: ext://sys.stderr
    formatter: basic
  audit_file:
    class: logging.FileHandler
    filename: p3_c14_audit.log
    encoding: utf-8
    formatter: basic
  formatters:
    basic:  # 定义了一个格式化器，名称为basic
      style: "{"
      format: "{levelname:s}:{name:s}:{message:s}"
    loggers:
      # 定义了两层的日志记录器：verbose和audit
      verbose:
        handlers: {console}
        level: INFO
      audit:
        handlers: {audit_file}
        level: INFO
